# Generated by Django 4.1.6 on 2023-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtag',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pagetag',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
