# Generated by Django 4.1.6 on 2023-02-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_tag_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note_tag_color',
        ),
    ]
