# Generated by Django 4.1.6 on 2023-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_event_created_at_event_is_active_event_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
