# Generated by Django 4.1.7 on 2023-02-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_pagetag_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetag',
            name='pages',
            field=models.ManyToManyField(blank=True, related_name='tags', to='notes.page'),
        ),
    ]
