# Generated by Django 4.1.5 on 2023-02-03 06:34

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tag_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#34eb67', 'green')]),
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='notes.tag'),
        ),
    ]
