# Generated by Django 4.1.7 on 2023-02-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_pagetag_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteBookTag',
        ),
    ]
