# Generated by Django 4.1.6 on 2023-02-13 23:47

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_delete_note_tag_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteBookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images')),
                ('color', colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=[('#000000', 'black'), ('#0000FF', 'Blue'), ('#C12FFF', 'Purple'), ('#34eb67', 'green'), ('#FF5B09', 'orange'), ('#FC1501', 'red'), ('#FFFF00', 'Yellow'), ('#FFA3EE', 'Pink')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_tag', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
