# Generated by Django 4.1.6 on 2023-02-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notebooktag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebooktag',
            name='user',
        ),
        migrations.AddField(
            model_name='notebooktag',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_tag', to='notes.page'),
            preserve_default=False,
        ),
    ]
