# Generated by Django 4.1.6 on 2023-02-14 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_notebooktag_user_notebooktag_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notebooktag',
            name='page',
        ),
        migrations.AddField(
            model_name='notebooktag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notebooks_tag', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
